name: mc2020
channels:
  - conda
  - conda-forge
dependencies:
  - cython
  - ffmpeg
  - ipywidgets
  - jupyter
  - matplotlib
  - numba
  - numpy
  - POT
  - progressbar2
  - python>=3.6
  - seaborn
  - scikit-learn
